/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as ConcesionariasRouteImport } from './routes/concesionarias'
import { Route as IndicadoresRouteImport } from './routes/indicadores'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcesionariasRoute = ConcesionariasRouteImport.update({
  id: '/concesionarias',
  path: '/concesionarias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/indicadores': typeof IndicadoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/indicadores': typeof IndicadoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/concesionarias': typeof ConcesionariasRoute
  '/indicadores': typeof IndicadoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benchmark' | '/concesionarias' | '/indicadores'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmark' | '/concesionarias' | '/indicadores'
  id: '__root__' | '/' | '/benchmark' | '/concesionarias' | '/indicadores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  ConcesionariasRoute: typeof ConcesionariasRoute
  IndicadoresRoute: typeof IndicadoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concesionarias': {
      id: '/concesionarias'
      path: '/concesionarias'
      fullPath: '/concesionarias'
      preLoaderRoute: typeof ConcesionariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  ConcesionariasRoute: ConcesionariasRoute,
  IndicadoresRoute: IndicadoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
